setwd("C:/xampp/htdocs/validasiImpor/output95")
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(RMySQL)
mydb = dbConnect(MySQL(), user='root', password='', dbname='validasiimpor', host='localhost')
rs = dbSendQuery(mydb, 'select CIFKG from hs14')
a = fetch(rs, n=-1)
qqnorm(a$CIFKG)
qqline(a$CIFKG, col="blue")
library(MASS)
boxcox(a$CIFKG[a$CIFKG > 0]~1)
library(car)
powerTransform(a$CIFKG[a$CIFKG > 0])
p<-powerTransform(a$CIFKG[a$CIFKG > 0])
y<-bcPower(a$CIFKG[a$CIFKG > 0],p$lambda)
q <- tableGrob(t(summary(y)))
mydataplot <- grid.arrange(q, ncol=1)
png(filename = "output.png", height=100)
plot(mydataplot)
dev.off()